# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.0.2.dev41+g74a0b6f.d20220921'
__version_tuple__ = version_tuple = (0, 0, 2, 'dev41', 'g74a0b6f.d20220921')
